language: java
sudo: false
install: true
jdk: openjdk11

# to keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar'
    - '$HOME/jvm'
    - '$HOME/maven'

before_cache:
  - rm -rf $HOME/.m2/repository/com/societegenerale/sonar/sslr
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

notifications:
  email: false

addons:
  sonarcloud:
    organization: "societe-generale"

#script: "chmod a+x ./travis.sh && ./travis.sh"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=societe-generale_sslr-yaml-parser
