language: java
sudo: false
install: true
jdk: openjdk11
# to keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar'
    - '$HOME/jvm'
    - '$HOME/maven'

before_cache:
  - rm -rf $HOME/.m2/repository/com/societegenerale/sonar/sslr
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

notifications:
  email: false

addons:
  sonarcloud:
    organization: "societe-generale"

script:
  - mvn -Pcoverage clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=societe-generale_sslr-yaml-parser

before_deploy:
  - release/createReleaseProperties.sh
  # Install GPG secrets so that we can sign during the release
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

deploy:
  provider: script
  script: mvn deploy -Dskiptests -Prelease --settings release/mvnsettings.xml -Darguments="-DskipTests"
  skip_cleanup: true
  on:
    tags: true
