language: java

# Use container-based infrastructure:
sudo: false

# to keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false

jdk: openjdk11

script: mvn install -B -v -e
